Repository flanksource/flanksource-ui, pull requests merged in 2023-04, with the labels that each got.

#1091 fix: remove schedule field from health check resource form
  src/api/schemaResources.ts
  src/components/SchemaResourcePage/SchemaResourceList.tsx
  src/components/SchemaResourcePage/resourceTypes.tsx
Labels: medium

#1029 937 config changes panel add virtual paging
  src/api/query-hooks/index.ts
  src/api/query-hooks/useGetConfigChangesByConfigChangeIdQuery.ts
  src/api/services/configs.ts
  src/components/ConfigChangeHistory/index.tsx
  src/components/ConfigChanges/Cells/ConfigChangeAgeCell.tsx
  src/components/ConfigChanges/Cells/ConfigChangeNameCell.tsx
  src/components/ConfigChanges/index.tsx
  src/components/ConfigDetailsChanges/ConfigDetailsChanges.tsx
  src/components/DataTable/Pagination/Pagination.tsx
  src/components/DataTable/index.tsx
  src/components/InfiniteTable/InfiniteTable.tsx
  src/components/Sidebars/configs.tsx
  src/components/Tabs/TabbedLinks.tsx
  src/pages/config/ConfigDetailsChangesPage.tsx
Labels: extra large

#1090 feat: add duration & status filters for check status history table
  src/api/query-hooks/useCheckStattiQuery.ts
  src/api/services/topology.ts
  src/components/Canary/CanaryPopup/CheckDetails.tsx
  src/components/Canary/CanaryPopup/StatusHistory/StatusHistory.tsx
  src/components/Canary/CanaryPopup/StatusHistory/StatusHistoryFilters.tsx
  src/components/ReactSelectDropdown/index.tsx
Labels: large

#1074 1060-sidebar-improvements-collapse-items-apart-default
  src/api/services/configs.ts
  src/components/Badge/CountBadge.tsx
  src/components/Badge/PillBadge.tsx
  src/components/Changelog/IncidentChangelog.tsx
  src/components/CollapsiblePanel/index.tsx
  src/components/ConfigAnalysisLink/ConfigAnalysisLink.tsx
  src/components/ConfigChanges/index.tsx
  src/components/ConfigCosts/index.tsx
  src/components/ConfigInsights/index.tsx
  src/components/ConfigSidebar/ConfigActionBar.tsx
  src/components/ConfigSidebar/ConfigDetails.tsx
  src/components/ConfigSidebar/index.tsx
  src/components/CostDetails/CostDetails.tsx
  src/components/IncidentDetails/DefinitionOfDone/IncidentsDefinitionOfDone.tsx
  src/components/IncidentDetails/IncidentDetailsPanel.tsx
  src/components/IncidentDetails/IncidentSidebar.tsx
  src/components/Insights/Insights.tsx
  src/components/Sidebars/configs.tsx
  src/components/Sidebars/incidents.tsx
  src/components/SlidingSideBar/SlidingSideBar.stories.tsx
  src/components/SlidingSideBar/index.tsx
  src/components/TopologyCard/TopologyCard.stories.tsx
  src/components/TopologyConfigChanges/index.tsx
  src/components/TopologyDetails/index.tsx
  src/components/TopologySidebar/ComponentTeams.tsx
  src/components/TopologySidebar/TopologyActionBar.tsx
  src/components/TopologySidebar/TopologyCost.tsx
  src/components/TopologySidebar/TopologyInsights.tsx
  src/components/TopologySidebar/TopologySidebar.tsx
  src/pages/TopologyPage.tsx
  src/pages/config/ConfigDetailsChangesPage.tsx
  src/pages/config/ConfigDetailsPage.tsx
  src/pages/config/ConfigInsightsList.tsx
  src/pages/config/configChanges.tsx
  src/pages/incident/IncidentDetails.tsx
  src/pages/incident/IncidentListPage.tsx
Labels: large

#1093 feat: add config changes filters
  src/api/query-hooks/index.ts
  src/api/services/configs.ts
  src/components/ChangesTypesDropdown/ChangeTypesDropdown.tsx
  src/components/ConfigChangeSeverity/ConfigChangeSeverity.tsx
  src/components/ConfigChangesFilters/ConfigChangesFilters.tsx
  src/components/ConfigTypesDropdown/index.tsx
  src/pages/config/ConfigChangesPage.tsx
  src/pages/index.ts
Labels: large
